---
title: My awesome title
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    intro: Get to know our authors!
  posts:
    title: Stories
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
url: http://yourdomain.com
twitter_username: awesomeinc
permalink: pretty
copyright: "© 2016 Awesome Inc."
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
