---
title: My awesome title
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    intro: Get to know our authors!
  posts:
    title: Stories
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    notes: 
    image: 
    excerpt: 
    starts at: 
    is featured: false
    author: 
    layout: post
email: your-email@domain.com
url: http://yourdomain.com
twitter_username: awesomeinc
permalink: date
copyright: "© 2016 Awesome Inc."
